// knowledge.js - Knowledge Base Page View Controller

const kbArticles = [
  {
    id: "KB-0045",
    category: "Authentication",
    title: "Resolving OAuth Signature Validation Issues",
    body: `<h3>Overview</h3>
    <p>OAuth authentication failures often occur due to signature mismatches or certificate validation timeouts. Standard systems reject payloads if the signature timestamp does not align within defined tolerances (clock skew).</p>
    
    <h3>Standard Remediation Steps</h3>
    <ol>
      <li>Verify signature credentials are correct and updated on target databases.</li>
      <li>Check the clock synchronization on both systems. A drift of > 60 seconds will invalidate authentication codes.</li>
      <li>Use the Network Time Protocol (NTP) to synchronize server system times.</li>
      <li>Ensure client applications are passing signatures in headers using standard Base64 encoding.</li>
    </ol>
    
    <h3>Diagnostic CLI command</h3>
    <pre style="background: var(--bg-app); border: 1px solid var(--border-color); padding: 10px; border-radius: 6px; font-family: monospace; font-size: 12px; margin-top: 8px;">
ntpdate -q pool.ntp.org
# Checks time drift statistics</pre>`
  },
  {
    id: "KB-0046",
    category: "Billing",
    title: "Double Subscription Processing & Checkout Callbacks",
    body: `<h3>Overview</h3>
    <p>Duplicate invoice generations are commonly tied to rapid double-clicks on checkout screens or asynchronous webhook retry loop lags in Stripe billing frameworks.</p>
    
    <h3>Resolution Rules</h3>
    <ul>
      <li>Identify double transactions in subscription logs matching idempotency tokens.</li>
      <li>Refund extra invoice elements directly through billing portal settings.</li>
      <li>Update customer seats limits internally to align with the single remaining subscription order.</li>
    </ul>`
  },
  {
    id: "KB-0047",
    category: "Database",
    title: "Database CPU Spike & Table lock investigation",
    body: `<h3>Overview</h3>
    <p>High write latency values (800ms+) on PostgreSQL or MySQL databases are typically generated by table locking queries missing indexes or unoptimized massive transactions.</p>
    
    <h3>Steps to Identify Faulty Lock Queries</h3>
    <ol>
      <li>Query active processes list to locate slow search operations.</li>
      <li>Perform a manual index rebuild or index creation on the queried schemas.</li>
      <li>Execute <code>VACUUM ANALYZE</code> to refresh system statistical query plans.</li>
    </ol>`
  },
  {
    id: "KB-0048",
    category: "API",
    title: "Webhook Gateway Outbound Blockages whitelisting",
    body: `<h3>Overview</h3>
    <p>Integrations with external servers might fail if outbound proxies or whitelisting layers filter outbound NAT IP gateways. Whitelist standard corporate blocks to prevent drop alerts.</p>
    
    <h3>IP Ranges for Firewall Configurations</h3>
    <p>Add these subnets to inbound server whitelists:</p>
    <code style="background: var(--bg-app); padding: 4px 8px; border-radius: 4px; font-family: monospace;">54.210.12.0/24, 34.225.80.0/24</code>`
  }
];

function initKnowledgeBaseModule() {
  // Render initial list
  renderKnowledgeArticles("All");

  // Search input actions
  document.getElementById("kb-search-bar").addEventListener("input", handleKBSearch);

  // Category selectors event delegation
  const categoriesList = document.getElementById("kb-category-list");
  categoriesList.addEventListener("click", (e) => {
    const item = e.target.closest(".kb-item");
    if (!item) return;

    // Toggle active state
    document.querySelectorAll(".kb-category-list .kb-item, #kb-category-list .kb-item").forEach(el => {
      el.classList.remove("active");
    });
    item.classList.add("active");

    const category = item.getAttribute("data-category");
    renderKnowledgeArticles(category);
  });
}

function renderKnowledgeArticles(category, query = "") {
  const container = document.getElementById("kb-docs-card");
  const filtered = kbArticles.filter(art => {
    const matchesCategory = category === "All" || art.category === category;
    const matchesQuery = art.title.toLowerCase().includes(query.toLowerCase()) || 
                         art.body.toLowerCase().includes(query.toLowerCase());
    return matchesCategory && matchesQuery;
  });

  if (filtered.length === 0) {
    container.innerHTML = `
      <div class="empty-state">
        <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M12 8v4M12 16h.01" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
        <h3>No documentation matching filter</h3>
        <p>Try searching using other keywords.</p>
      </div>
    `;
    return;
  }

  // Render first matching doc automatically in viewer
  const firstDoc = filtered[0];
  container.innerHTML = `
    <h2 id="kb-doc-title" style="font-size: 20px; font-weight: 700; margin-bottom: 12px;">${firstDoc.title}</h2>
    <div style="font-size: 12px; color: var(--accent-primary); font-weight: 700; margin-bottom: 16px; text-transform: uppercase;">
      Category: ${firstDoc.category} | Article ID: ${firstDoc.id}
    </div>
    <div id="kb-doc-body" style="font-size: 14px; line-height: 1.7; color: var(--text-secondary);">
      ${firstDoc.body}
    </div>
  `;
}

function handleKBSearch(e) {
  const query = e.target.value;
  
  // Highlight active category
  const activeCategoryEl = document.querySelector("#kb-category-list .kb-item.active");
  const activeCategory = activeCategoryEl ? activeCategoryEl.getAttribute("data-category") : "All";
  
  renderKnowledgeArticles(activeCategory, query);

  // If query is long (like a sentence/ticket description), simulate real-time AI solution retrieval
  const aiPanel = document.getElementById("kb-ai-solution-panel");
  if (query.trim().length > 10) {
    aiPanel.style.display = "block";
    document.getElementById("kb-ai-content").innerHTML = `
      <strong>Analyzing query query context...</strong> Searching vectorized semantic nodes matching "<em>${query}</em>"...<br><br>
      <strong>Dynamic AI Prototyped Solution:</strong> Recommended verifying payload routing blocks. It appears the target client endpoint has a timeout configurations setting set to < 500ms, causing handshake timeouts. Increase webhook endpoint timeout configurations.
    `;
  } else {
    aiPanel.style.display = "none";
  }
}

// Expose model globally
window.TicketNovaKB = {
  init: initKnowledgeBaseModule
};
